library check_in_presentation;

import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:ui' as UI;
import 'dart:typed_data';
import 'dart:io';
import 'dart:collection';

import 'package:beamer/beamer.dart';
import 'package:check_in_presentation/core/circle_clusters/circle_helper.dart';
import 'package:check_in_presentation/core/circle_clusters/circle_previewer.dart';
import 'package:check_in_presentation/core/voucher_widget.dart';
import 'package:check_in_presentation/explore_core_widgets/components/browse_components/browse_section_widget.dart';
import 'package:check_in_presentation/explore_core_widgets/components/browse_components/feed_components/activities_feed_widget.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:alphabet_list_scroll_view/alphabet_list_scroll_view.dart';
import 'package:check_in_application/misc/update_services/invitiation_services/invitation_service_bloc.dart';
import 'package:check_in_application/misc/watcher_services/stripe_watcher_services/stripe_payment_watcher_bloc.dart';
import 'package:check_in_application/un_auth/watcher_services/attendee_watcher_service/attendee_manager_watcher_bloc.dart';
import 'package:check_in_application/auth/update_services/listing_update_create_services/settings_update_create_services/activity_settings/vendor_settings/vendor_settings_form_bloc.dart';
import 'package:check_in_presentation/listing_manager_core_widgets/component/listing_card.dart';
import 'package:check_in_presentation/listing_manager_core_widgets/component/map_options.dart';
import 'package:check_in_presentation/reservation_profile_core_widgets/components/filter_components/reservation_filter_sort_widget.dart';
import 'package:collection/collection.dart';
import 'package:confetti/confetti.dart';
import 'package:fluster/fluster.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:avatar_stack/avatar_stack.dart';
import 'package:check_in_application/auth/update_services/listing_update_create_services/settings_update_create_services/activity_settings/activity_settings_form_bloc.dart';
import 'package:check_in_application/check_in_application.dart';
import 'package:check_in_credentials/check_in_credentials.dart';
import 'package:check_in_domain/check_in_domain.dart';
import 'package:check_in_domain/domain/misc/attendee_services/form/merchant_vendor/custom_availability/mv_custom_availability.dart';
import 'package:check_in_domain/domain/misc/attendee_services/form/merchant_vendor/booth_payments/mv_booth_payments.dart';
import 'package:check_in_domain/domain/misc/attendee_services/form/merchant_vendor/custom_options/mv_custom_options.dart';
import 'package:check_in_domain/domain/misc/explore_services/filter/explore_filter_item.dart';
import 'package:check_in_domain/domain/misc/explore_services/value_objects.dart';
import 'package:check_in_domain/domain/misc/attendee_services/attendee_item/attendee_item.dart';
import 'package:check_in_domain/domain/misc/stripe/receipt_services/receipt/receipt_pdf_generator.dart';
import 'package:check_in_domain/domain/misc/filter_services/vendor_contact_filter_model.dart';
import 'package:check_in_domain/domain/misc/reservation_services/reservation_filter/reservation_filter_sort_widget.dart';
import 'package:check_in_facade/check_in_facade.dart' as facade;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dotted_border/dotted_border.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:flutter_chat_ui/flutter_chat_ui.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter_contacts/flutter_contacts.dart' as con;
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_switch/flutter_switch.dart';
import 'package:geolocator/geolocator.dart';
import 'package:glowy_borders/glowy_borders.dart';
import 'package:image_picker/image_picker.dart';
// import 'package:implicitly_animated_reorderable_list_2/implicitly_animated_reorderable_list_2.dart';
// import 'package:implicitly_animated_reorderable_list_2/transitions.dart';
import 'package:infinite_scroll_pagination/infinite_scroll_pagination.dart';
import 'package:intl/intl.dart';
import 'package:intl/number_symbols_data.dart';
import 'package:map_launcher/map_launcher.dart' as map;
import 'package:material_floating_search_bar_2/material_floating_search_bar_2.dart';
import 'package:video_player/video_player.dart';
// import 'package:pattern_formatter/pattern_formatter.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:patterns_canvas/patterns_canvas.dart';
import 'package:phone_form_field/phone_form_field.dart';
import 'package:shimmer/shimmer.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_chat_types/flutter_chat_types.dart';
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';
import 'package:check_in_application/auth/update_services/listing_update_create_services/attendee_update_create_services/listing_attendee_form_bloc.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import 'package:syncfusion_flutter_charts/charts.dart' as charts;
import 'package:dartz/dartz.dart' as dart;
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:check_in_domain/domain/misc/attendee_services/attendee_item/attendee_item.dart';
import 'package:jumping_dot/jumping_dot.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/available_times_widget.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/booth_payments_widget.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/disclaimer_options_widget.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/open_close_dates_widget.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/welcome_message_widget.dart';
import 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/discount_code_widget.dart';
import 'activity_core_widgets/create_activity/create_activity_screen_2.dart';
import 'core/image_picker_core.dart' if (dart.library.html) 'core/image_picker_core_for_web.dart';
import 'core/ios_core/file_picker.dart' if (dart.library.html) 'core/web_core/payment_core/file_picker.dart';
import 'core/ios_core/single_image_selector_widget_mobile.dart' if (dart.library.html) 'core/web_core/single_image_selector_widget_web.dart';
import 'core/pdf_viewer_mobile.dart' if (dart.library.html) 'core/pdf_viewer.dart';
import 'package:auth_buttons/auth_buttons.dart';
import 'core/profile_creator_template/profile_creator_template.dart';
import 'core/profile_creator_template/profile_creator_template_helper.dart';
import 'core/profile_creator_template/template_components/profile_layout_component.dart';
import 'core/profile_creator_template/template_components/profile_section_item.dart';
import 'core/profile_creator_template/template_components/profile_section_item.dart';
import 'core/web_core/payment_core/widgets/embedded_stripe_checkout.dart' if (dart.library.html) 'core/web_core/payment_core/widgets/embedded_stripe_checkout_for_web.dart';
import 'core/calendar_event_core.dart' if (dart.library.html) 'core/calendar_event_core_web.dart';
import 'core/alert_dialog_helper.dart' if (dart.library.html) 'core/alert_dialog_helper_web.dart';
import 'core/ios_core/refresh_mobile.dart' if (dart.library.html) 'core/web_core/refresh_web.dart';
import 'core/router_helper.dart';
import 'package:lottie/lottie.dart' as lottie;
import 'package:flutter_wallet_card/flutter_wallet_card.dart';
import 'package:pass_flutter/pass_flutter.dart';
import 'package:badges/badges.dart' as badges;
import 'package:url_launcher/url_launcher_string.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:flutter_chat_types/flutter_chat_types.dart' as types;
import 'package:reservation_post/inputs/input.dart' as post;
import 'package:reservation_post/inputs/media_attatchment_preview.dart';
import 'package:reservation_post/models/media_mode.dart';
import 'package:reservation_post/reservation_post.dart';
import 'package:check_in_domain/domain/auth/reservation_manager/reservation_post/image_post.dart';
import 'package:check_in_domain/domain/auth/reservation_manager/post.dart';
import 'package:check_in_domain/domain/misc/stripe/tax_calculation/stripe_tax_calculation.dart';
import 'package:check_in_domain/domain/misc/discount_code_service/discount_code_item.dart';
import 'package:check_in_application/auth/update_services/booked_reservation_services/booked_reservation_form_bloc.dart';
import 'package:scroll_to_index/scroll_to_index.dart';
import 'package:check_in_domain/domain/auth/reservation_manager/reservation_post/system_post.dart';
import 'package:check_in_domain/domain/misc/messages_services/messenger_filter/rooms_filter_sort_widget.dart';
import 'core/ios_core/image_selector_widget_mobile.dart' if (dart.library.html) 'core/web_core/image_selector_widget_web.dart';
import 'explore_core_widgets/components/browse_components/filter_components/activities_filter_sort_helper.dart';
import 'explore_core_widgets/components/browse_components/filter_components/vendor_filter_sort_helper.dart';
import 'explore_core_widgets/components/template_components/explore_search_main_layout.dart';
import 'explore_core_widgets/components/template_components/explore_search_shell.dart';
import 'explore_core_widgets/components/browse_components/feed_components/vendor_feed_widget.dart';
import 'share_core/mobile_share_widget.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'core/ios_core/new_payment_method_widget_mobile.dart' if (dart.library.html) 'core/web_core/payment_core/widgets/new_payment_method_widget_web.dart';
import 'package:hovering/hovering.dart';


part 'check_in_theme_model.dart';
part 'misc.dart';
part 'reservation_listing_core_widgets/reservation_card.dart';
part 'reservation_listing_core_widgets/reservation_listing_space.dart';
part 'reservation_listing_core_widgets/reservation_listing_pricing_cancellation.dart';
part 'reservation_listing_core_widgets/reservatioin_listing_rules.dart';
part 'reservation_listing_core_widgets/create_new_reservation_helper.dart';
part 'reservation_listing_core_widgets/reservation_listing_calendar.dart';
part 'reservation_listing_core_widgets/reservation_listing_selected_slots.dart';
part 'reservation_listing_core_widgets/reservation_manager_helper.dart';
part 'reservation_profile_core_widgets/reservation_profile_spaces.dart';
part 'reservation_profile_core_widgets/components/filter_components/reservation_filter_header.dart';
part 'reservation_profile_core_widgets/components/widgets/reservation_details_widget.dart';
part 'reservation_listing_core_widgets/reservation_notification_helper.dart';
part 'reservation_profile_core_widgets/reservation_profile_helper.dart';
part 'reservation_profile_core_widgets/components/widgets/reservation_activity_info_widget.dart';
part 'reservation_profile_core_widgets/components/widgets/reservation_footer_widget.dart';
part 'reservation_listing_core_widgets/resrervation_search_helper.dart';
part 'reservation_profile_core_widgets/components/helper/reservation_helper_core.dart';
part 'reservation_profile_core_widgets/components/pop_over_screen/reservation_affiliate_onboarding_widget.dart';
part 'reservation_profile_core_widgets/components/widgets/reservation_info_widget.dart';
part 'reservation_profile_core_widgets/reservation_helper.dart';
part 'reservation_profile_core_widgets/reservations_screen.dart';
part 'reservation_profile_core_widgets/components/reservation_results_main.dart';
part 'messenger_core_widgets/messenger_helper.dart';

part 'messages_core_widgets/direct_chat_screen.dart';
part 'messages_core_widgets/direct_chat_helper.dart';
part 'messages_core_widgets/post_helper.dart';
part 'messages_core_widgets/post_widget_builder.dart';
part 'messages_core_widgets/rooms_helper_core.dart';
part 'messages_core_widgets/rooms_screen.dart';
part 'messages_core_widgets/pop_over/new_chat_pop_over/send_new_chat_container.dart';
part 'messages_core_widgets/pop_over/new_chat_pop_over/new_chat_pop_over_helper.dart';
part 'messages_core_widgets/pop_over/create_new_chat.dart';
part 'messages_core_widgets/components/chat_headers.dart';
part 'messages_core_widgets/components/chat_details_sidebar.dart';
part 'messages_core_widgets/components/filter_components/rooms_filter_header.dart';
part 'messages_core_widgets/components/rooms_components/channel_rooms_list.dart';
part 'messages_core_widgets/components/rooms_components/direct_rooms_list.dart';
part 'messages_core_widgets/components/rooms_components/group_rooms_list.dart';
part 'messages_core_widgets/components/rooms_components/rooms_component_helper.dart';
part 'messages_core_widgets/components/rooms_components/all_rooms_list.dart';

part 'listing_manager_core_widgets/space_option_info_widgets.dart';
part 'listing_manager_core_widgets/profile_manager_dashboard.dart';
part 'listing_manager_core_widgets/facility_listing_settings_helper.dart';
part 'listing_manager_core_widgets/helpers/check_in_edit_helper.dart';
part 'listing_manager_core_widgets/helpers/custom_rule_edit_helper.dart';
part 'listing_manager_core_widgets/payment_info_widget.dart';
part 'listing_manager_core_widgets/helpers/cancellation_edit_widgets.dart';
part 'listing_manager_core_widgets/helpers/check_in_form_edit_widget.dart';
part 'listing_manager_core_widgets/helpers/custom_rule_edit_widget.dart';
part 'listing_manager_core_widgets/component/facility_overview_info_widget.dart';
part 'listing_manager_core_widgets/helpers/facility_preview_screen_helper.dart';
part 'listing_manager_core_widgets/helpers/listing_helper.dart';
part 'listing_manager_core_widgets/component/map_listing_component.dart';
part 'profile_core_widgets/helper/general_profile_helper.dart';
part 'profile_core_widgets/profile_settings_screen_helper.dart';
part 'profile_core_widgets/components/review_current_profile.dart';
part 'profile_core_widgets/helper/profile_helper_widget.dart';
part 'profile_core_widgets/components/vendor_profile_creator_editor.dart';
part 'profile_core_widgets/components/edit_socials_profile.dart';
part 'profile_core_widgets/edit_selected_profile.dart';
part 'profile_core_widgets/helper/profile_settings_helper.dart';
part 'profile_core_widgets/components/general_small_activities_paging_widget.dart';
part 'profile_core_widgets/components/general_small_facilities_paging_widget.dart';
part 'profile_core_widgets/components/general_profile_widget.dart';
part 'profile_core_widgets/components/general_profile_creator_editor.dart';
part 'profile_core_widgets/pop_over_screen/gain_access_to_owners_app.dart';
part 'profile_core_widgets/pop_over_screen/vendor_application_requests_container.dart';
part 'profile_core_widgets/pop_over_screen/reservations_show_all_pagining.dart';
part 'profile_core_widgets/profile_main_container.dart';
part 'profile_core_widgets/helper/profile_edit_helper.dart';
part 'profile_core_widgets/components/vendor_profile_widget.dart';
part 'profile_core_widgets/profile_settings/components/personal_information_profile.dart';
part 'profile_core_widgets/profile_main_helper.dart';
part 'profile_core_widgets/profile_settings/components/payments_widget/payment_methods_widget.dart';
part 'calendar_core_widgets/date_time_core_helper.dart';

part 'core/pagaing_with_arrows_core.dart';
part 'core/search_user_profile_widget.dart';
part 'core/phone_field_view_widget.dart';
part 'core/fliter_selection_widget.dart';
part 'core/web_core/payment_core/widgets/payment_method_widget.dart';
part 'core/web_core/payment_core/widgets/payment_history_widget.dart';
part 'core/web_core/payment_core/check_out_payment_flow_widget.dart';
part 'core/form_creator_template/form_creator_template_helper.dart';
part 'core/form_creator_template/form_creator_template.dart';
part 'core/indicator_widget.dart';
part 'core/main_form_buttons_widget.dart';
part 'core/list_wheel_scroll_view.dart';
part 'core/location_form_field.dart';
part 'core/search_profiles_widget.dart';
part 'core/attendee_type_helper_widget.dart';
part 'core/web_core/payment_core/check_out_payment_helper.dart';
part 'core/attendee_creator_template/create_new_main.dart';
part 'core/completed_task_animation_widget.dart';
part 'core/web_core/payment_core/widgets/payment_processing_widget.dart';
part 'core/check_out_view_widget.dart';
part 'core/animated_complete_button.dart';
part 'core/on_boarding_pop_over_widget.dart';
part 'core/webview_controller_widget.dart';
part 'core/responsive/responsive.dart';
part 'core/tabHelper.dart';
part 'core/loading_core/loading_widgets.dart';
part 'core/show_more_text_button.dart';
part 'core/contact_site_footer_core.dart';
part 'core/sticky_header_core.dart';

part 'share_core/share_core.dart';

part 'share_core/shared_screenshot_editor_widget.dart';

part 'facility_core_widget/facility_preview_screen.dart';
part 'facility_core_widget/components/add_new_reservation_slots.dart';
part 'facility_core_widget/components/facility_activity_programming.dart';
part 'activity_core_widgets/create_activity/components/select_facility_list_screen.dart';
part 'activity_core_widgets/create_activity/create_activity_screen.dart';
part 'activity_core_widgets/create_activity/create_activity_screen_helper.dart';

part 'activity_core_widgets/activity_result_main_helper.dart';
part 'activity_core_widgets/activity_result_main.dart';
part 'activity_core_widgets/activity_icon_helper_widgets.dart';
part 'activity_core_widgets/activity_instrutctor_helper_widgets.dart';
part 'activity_core_widgets/activity_listing_settings_helper.dart';
part 'activity_core_widgets/activity_background_info_settings_widget.dart';
part 'activity_core_widgets/activity_requirements_setting_widget.dart';
part 'activity_core_widgets/activity_reservation_settings_widget.dart';
part 'activity_core_widgets/activity_visibility_settings_widget.dart';
part 'activity_core_widgets/activity_cancellation_setting_widget.dart';
part 'activity_core_widgets/activity_custom_rule_info_widget.dart';
part 'activity_core_widgets/activity_check_in_info.dart';
part 'activity_core_widgets/activity_general_rules_widget.dart';
part 'activity_core_widgets/activity_attendee_type_widget.dart';
part 'activity_core_widgets/activity_ticket_attendee_widget.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/widgets/custom_options_widget.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor/create_new_vendor_merchant.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor/vendor_merchant_helper.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/vendor_merchant_form_helper.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_vendor_form/create_new_vendor_merchant_form.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_partner/create_new_partner.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_instructor/create_new_instructor_form.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_instructor/instructor_helper.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_instructor/create_new_experience.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_instructor/create_new_certification.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_ticket_holder/create_new_ticket_holder_attendee.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_ticket_holder/activity_ticket_pricing_cancellation_helper.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/present_ticket/present_attendee_ticket_widget.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_attendee/create_new_activity_attendee.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/create_new_attende_helper.dart';
part 'activity_core_widgets/pop_over_main_container_widgets/request_partnership_attendee/request_new_partner_attendee.dart';
part 'activity_core_widgets/manage_activity_attendee/widgets/activity_application_settings_widget.dart';
part 'activity_core_widgets/activity_preview/components/background_images_pageview.dart';
part 'activity_core_widgets/activity_preview/components/share_link_widget.dart';
part 'activity_core_widgets/activity_preview/activity_preview_screen.dart';
part 'activity_core_widgets/activity_preview/activity_preview_screen_helper.dart';
part 'activity_core_widgets/activity_preview/components/similar_activities_list.dart';
part 'activity_core_widgets/activity_attendees/activity_attendees_list_helper.dart';
part 'activity_core_widgets/activity_attendees/activity_attendees_list_screen.dart';
part 'activity_core_widgets/activity_attendees/activity_attendees_result_main.dart';
part 'activity_core_widgets/manage_activity_attendee/manage_attendee_settings_sub_container.dart';
part 'activity_core_widgets/manage_activity_attendee/manage_attendee_settings_helper.dart';
part 'activity_core_widgets/manage_activity_attendee/widgets/activity_application_helper.dart';
part 'activity_core_widgets/settings/activity_vendor_form_widget/activity_vendor_forms_widget.dart';
part 'activity_core_widgets/settings/activity_vendor_form_widget/activity_vendor_form_helper.dart';
part 'activity_core_widgets/settings/activity_type_widget/select_activity_type_widget.dart';
part 'activity_core_widgets/settings/activity_rules_widget/review_activity_rule_preset.dart';
part 'activity_core_widgets/settings/activity_rules_widget/create_new_activity_rule.dart';
part 'activity_core_widgets/settings/activity_rules_widget/create_new_activity_game_rule.dart';
part 'activity_core_widgets/settings/activity_rules_widget/activity_general_rules_widget.dart';
part 'activity_core_widgets/settings/activity_rules_widget/activity_general_rules_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/select_reservation_overview_widget.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/review_reservation_overview_widget.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/review_reservation_hint.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/reservation_helper.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/create_ticket_reservation_widget.dart';
part 'activity_core_widgets/settings/activity_reservation_widget/create_pass_reservation_widget.dart';
part 'reservation_profile_core_widgets/components/reservation_previewer_list_widget.dart';
part 'activity_core_widgets/settings/activity_requirements_widget/requirements_settings_widget.dart';
part 'activity_core_widgets/settings/activity_requirements_widget/requirements_settings_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_pricing_widget/review_pricing_breakdown_widget.dart';
part 'activity_core_widgets/settings/activity_pricing_widget/widget/select_facility_cost_cancellation_widget.dart';
part 'activity_core_widgets/settings/activity_pricing_widget/widget/activity_pricing_per_hour_widget.dart';
part 'activity_core_widgets/settings/activity_presets/activity_presetup_game_widget.dart';
part 'activity_core_widgets/settings/activity_payment_widget/activity_payments_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_custom_rules_widgets/custom_rule_info_widget.dart';
part 'activity_core_widgets/settings/activity_custom_rules_widgets/custom_rule_info_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_check_in_widget/chexk_ins_info_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_check_in_widget/check_ins_info_widget.dart';
part 'activity_core_widgets/settings/activity_cancellation_widget/select_cancellation_settings_widget.dart';
part 'activity_core_widgets/settings/activity_cancellation_widget/select_cancellation_settings_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_background_mobile_widget/background_info_settings_widget.dart';
part 'activity_core_widgets/settings/activity_background_mobile_widget/activity_background_preview.dart';
part 'activity_core_widgets/settings/activity_availability_widget/activity_duration_helper.dart';
part 'activity_core_widgets/settings/activity_availability_widget/widget/activity_weekday_list_widget.dart';
part 'activity_core_widgets/settings/activity_availability_widget/widget/activity_session_editor_widget.dart';
part 'activity_core_widgets/settings/activity_availability_widget/widget/activity_hours_filter_widget.dart';
part 'activity_core_widgets/settings/activity_attendee_widget/select_attendee_type_widget.dart';
part 'activity_core_widgets/settings/activity_attendee_widget/select_attendee_type_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_attendee_widget/create_ticket_attendee_type.dart';
part 'activity_core_widgets/settings/activity_attendee_widget/create_ticket_attendee_mobile_widget.dart';
part 'activity_core_widgets/settings/activity_access_visibility_widgets/access_visibility_info_settings_widget.dart';
part 'activity_core_widgets/settings/activity_access_visibility_widgets/access_visibility_info_settings_mobile_widget.dart';
part 'activity_core_widgets/settings/activuty_settings_mobile/activity_settings_mobile_container.dart';
part 'activity_core_widgets/settings/activuty_settings_mobile/activity_settings_screen_mobile.dart';
part 'activity_core_widgets/settings/activuty_settings_mobile/activity_settings_screen_mobile_helper.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_ticket_sub_container_widget.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_attendee_ticket_results_main.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_ticket_helper.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_ticket_results_main.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_attendee_ticket_settings_container_widget.dart';
part 'activity_core_widgets/manage_activity_tickets/activity_ticket_settings_container_widget.dart';


part 'explore_core_widgets/search_explore_helper_core.dart';
part 'explore_core_widgets/explore_discovery_main_dashboard.dart';
part 'explore_core_widgets/discovery_search_helper.dart';
part 'explore_core_widgets/components/browse_components/browse_filter_app_bar.dart';
part 'explore_core_widgets/components/browse_components/browse_main_container_widget.dart';
part 'explore_core_widgets/components/browse_components/browse_hero_main_widget.dart';
part 'explore_core_widgets/components/browse_components/filter_components/activities_filter_date_range_widget.dart';
part 'explore_core_widgets/components/browse_components/browse_listigs_widget.dart';
part 'explore_core_widgets/components/browse_components/browse_vendors_widget.dart';
part 'explore_core_widgets/components/browse_components/browse_full_bleed_widget.dart';
part 'explore_core_widgets/components/listing_components/listing_result_main_card.dart';
part 'explore_core_widgets/components/listing_components/listing_result_main.dart';
part 'explore_core_widgets/components/listing_components/listing_quick_preview.dart';
// part 'activity_core_widgets/settings/activuty_settings_mobile/activity_settings_screen_mobile_helper.dart';


part 'invite_widgets/send_invitation_request.dart';
part 'invite_widgets/send_invitation_request_helper.dart';
part 'invite_widgets/contacts_widget.dart';


part 'attendee_core_widgets/attendee_profile_helper.dart';

part 'account/login_signup_core.dart';
part 'account/login_forgot_password_email.dart';
part 'account/login_email_core.dart';
part 'account/on_boarding_activities_profile.dart';

part 'location_core_widgets/search_locations_google_places.dart';


part 'dashboard_core_widgets/counter_badge_widget.dart';

part 'booking_widgets/booking_slot_helper.dart';

part 'widget_transitions/create_widget_transitions.dart';

part 'map_core_widgets/map_helper.dart';